Routers
rnretina/Spbu2SemesterHW pull request #2
Opened 2022-07-22 16:24 UTC by rnretina

2022-07-23 14:43 UTC, yurii-litvinov requested changes
Тут надо было консольную утилиту, которая как параметр командной строки принимает путь до входного файла, так что надо ещё Main

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/Routers/Heap.cs
> +            return new T();
Попытка извлечь значение из пустой кучи кажется неправильной. Может, стоит исключения бросать

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/Routers/Heap.cs
> +        if (_list.Count == 0 ||_list[largest].CompareTo(_list[index]) == 0)
```suggestion
        if (_list.Count == 0 || _list[largest].CompareTo(_list[index]) == 0)
```

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/Routers/Heap.cs
> +        BuildHeap(largest);
Вообще, тут эту рекурсию очень просто превратить в цикл while, а нерекурсивные алгоритмы при прочих равных лучше рекурсивных (меньше оверхед на вызов, невозможно переполнение стека). Но можно не править.

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/Routers/RoutersNetwork.cs
> +    public RoutersNetwork(string inputPath)
```suggestion
    public readonly Dictionary<Edge, int> TreeEdges = new();
    
    public RoutersNetwork(string inputPath)
```

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/Routers/RoutersNetwork.cs
> +    // я не придумал, как тестировать по-другому
Ну, паблик-поля в любом случае запрещены, могли бы это хотя бы свойством с геттером сделать. Но поскольку сам Dictionary мутабельный, это позволит извне влезть и добавить/удалить рёбра, поэтому правильнее было бы сделать метод, возвращающий ребро по запросу или список рёбер (и строить его прямо по ходу, чтобы потом можно было менять, не влияя на сам RoutersNetwork) или что-то такое.

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/Routers/RoutersNetwork.cs
> +                ew.Write("routers network were unconnected");
```suggestion
                Console.Error.Write("routers network were unconnected");
```
А то какое-то странное имя переменной

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/Routers/RoutersNetwork.cs
> +        using (var sw = new StreamWriter(targetPath, false))
```suggestion
        using var sw = new StreamWriter(targetPath, false);
```
И дальше без лишнего отступа. using со скобками имеет смысл использовать только тогда, когда ресурс надо закрыть до завершения метода.

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/RoutersTest/RoutersNetworkTest.cs
> +        var rn = new RoutersNetwork("TestBigGraphWithEqualEdges.txt");
Лучше не сокращать имена, вообще никогда. Написать надо один раз, а догадываться, что они значат, может быть нужно тысячи раз в реальных проектах

2022-07-23 14:43 UTC, yurii-litvinov commented on Homework5/Routers/RoutersTest/RoutersNetworkTest.cs
> +            { new Edge(4, 6, 7), 7 }, // тут возможно ребро (5,6) 7 , но программа построит дерево с ребром (4, 6) 7
Стоило подобрать тест, где нет места случайности

2022-07-23 20:59 UTC, rnretina commented on Homework5/Routers/Routers/RoutersNetwork.cs
> +        using (var sw = new StreamWriter(targetPath, false))
я так делал изначально, но после этого из 5 тестов падают 3 с ошибкой The process cannot access the file ...\output, как будто бы StreamWriter не диспозится по завершении работы метода и несколько тестов пытаются туда писать одновременно

2022-07-23 21:34 UTC, rnretina commented
убрал еще совсем словари, которые были нужны только для удобства тестирования. вроде если граф был бы очень большим, то со словарём было больно работать. но теперь в тестах надо писать ребра в порядке их добавления

2022-07-26 22:41 UTC, rnretina commented
еще почему-то во всех коммитах .idea пытается добавиться, хотя она есть в .gitignore

2022-08-08 10:24 UTC, yurii-litvinov approved these changes
В целом всё правильно, так что зачтена.

2022-08-08 10:24 UTC, yurii-litvinov commented on Homework5/Routers/Routers/Edge.cs
> +    public int Weight { get; } = 0;
Интересно, почему Vertex0 и Vertex1 поля, а Weight — свойство с геттером. Типа входную/выходную вершину можно менять, а вес — нет?

2022-08-08 10:24 UTC, yurii-litvinov commented on Homework5/Routers/Routers/Main.cs
> +routersNetwork.BuildNetwork(args[1]);
Здесь я вижу несколько наивное предположение, что вызывающий эту программу не облажался :) Всегда проверяйте входные параметры.

2022-08-08 10:24 UTC, yurii-litvinov commented on Homework5/Routers/Routers/RoutersNetwork.cs
> +    private readonly List<Edge> _edges = new ();
```suggestion
    private readonly List<Edge> _edges = new();
```

2022-08-08 10:24 UTC, yurii-litvinov commented on Homework5/Routers/Routers/RoutersNetwork.cs
> +        using var sw = new StreamWriter(targetPath, false);
```suggestion
        using var streamWriter = new StreamWriter(targetPath, false);
```
Не сокращайте имена, даже если очень хочется :)

2022-08-08 10:37 UTC, merged