Stack Calculator
rnretina/Spbu2SemesterHW pull request #4
Opened 2022-07-22 17:00 UTC by rnretina

2022-07-22 17:03 UTC, rnretina commented
я не понял, как сюда попали предыдущие домашки, потому что ветку с этой домашкой создавал из ветки main, в которую еще не замерджил остальные домашки((

2022-07-23 12:34 UTC, yurii-litvinov requested changes
Судя по https://github.com/rnretina/Spbu2SemesterHW/network, эта ветка всё-таки была отведена от роутеров. Постарайтесь аккуратно сделать как надо. Можно отвести от main новую ветку и выложить туда код стекового калькулятора (так, правда, история коммитов потеряется). Без потери истории можно аккуратно воспользоваться `git cherry-pick`, но именно что аккуратно --- она создаёт _копию_ коммита, так что если накосячить, сильно попортит историю.

2022-07-23 12:34 UTC, yurii-litvinov commented on Homework2/StackCalculator/StackCalculator/ListStack.cs
> +        _head = _head.Next;
Ругается на то, что выше выражалась неувереннность в ненулловости head, а тут нет

2022-07-23 12:34 UTC, yurii-litvinov commented on Homework2/StackCalculator/StackCalculator/StackCalculator.cs
> +                    // тут по идее бросится исключение и поймается в мейне
Это уже неправда :)

2022-07-23 12:34 UTC, yurii-litvinov commented on Homework2/StackCalculator/StackCalculatorTest/StackCalculatorTest.cs
> +        Assert.That(ex.Message, Is.EqualTo("The number of operands must be greater by 1 than amount of operations"));
ex вроде как надо сначала проверить на null

2022-07-23 19:59 UTC, closed without merging